version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      lDYDSlCe/5IPxhNKCa32/faTGB10S3fMMg7WkQ8MZnxaVwvbK3cKbBbdXv6LfffzP3+L0lZh4UXYmIRC11kgw8pWOihxpEX9itQPZQlrqLOsI3048pIn98K4FwByFSCp/IyJWXEmCvfjTSi7MDuMjRaWPS0KqlQm99dUg5ez7A+KYvtrDk7fEDH2Cqlu6qh+xqaFSV9e9YuZQY8mjnKrzmXNg/c4IaF/uDZg4eeiscJKgCx3XFVIleiPemE+jiKUewmdSme8/jTCq/b0S5xDX9U4XI01sjKKVadNnyTrzwqiakh/HWgXOrI7s9CzDo8M583i6Bv0aIqDPWPj1MzIg5Jv5kLylx9vQ5sWEUzGK6+jP7L6t3kSghVAAq4O5c2vDM5KwHrhS3i1cqA5HyTllod984I3vZHnKAij+VXnTpRpiMS3vw9QNtCO6+GArVSo8IfWLDU4CIE2BctN0l9C+UdqfNYR6gtB3OP6O0j33tl2+pJAiP2hiILkvItibQ5wSKPqrHqGyVasUFO+w5hvZaLaFhRdjlYmhM15Gkl7tpZ4qy0kxm0pUM/ocoL3hlnn+KMizHITxgw05bzegIqtLvpzm9CvQmeZCTsT89mgL5TPhHJbowTBtvcDhhan2KzosPVJkC3yI0RvuoLfrkvXp+kYgPjkLhKqB2bAkYVwGUA=
