version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      S/3i6kDq2q3/sEN74qLtXM+aLO8Nvob6U19oyodUQTutMDmU4Pc68XRbtZO7uSxtrb6ntYfsPeY6urAuyd5Dhj/xJVAgzSWqpwF2QEjPwQvIq0P3Jmo086DM9YltXUn+BNJ/HXeJNFPGsLI3HUPLTDxPI3vCSHY5ds/nuRvjoNBs/r32aQB2rm+Gia2LwaVzCeFVBc/DRuMzK2V9dugKTbeFkSTaQL70ftDVtVAXjoOlLYTOr2W/1+N+L68lDXW4Veph+KRbhfumldMxhHraLnCRDBGOx9i3vDDl7LR5gWsMYdUHYFDXQHOAwWaG8mT0pz9HrvJJ91wzOjOsX4nOCxCQEkA4jGlAyL8CatG7oSFOIsr5MfcVxp9L3oaM5N1h5N6/4aPMO2Z/X42AhBDmQqPb/TVh8pj8W3W4v9qIBEJPHnb3JqWuUJ5+VrBKuwgOaJ02/Zo4LyX1PhUfT1EpNskCrZkY1yXtCxcGWE/kMwvYBLkcNI5fHFVmJcFuFjsUzNDFc+zo/iqEaSFJeEupw7KcloLGkO/pFZl7meU1Rvn/0x72iKo4ibrZX1AoBrOrRKQZnz1eIoHlJ0hbemJkpERnmcdPakI3KMxPs5ZD+ahs0Llfer6MAZ1pg9gxVmd3s2frWGEJUKohyArdbRxzZeHUJnswC7rc8jhJUSJGCBA=
